/*INSERIM CATEGORIES*/

/*CIENCES, ESPORTS, ENTRETENIMENT, HISTORIA, GEOGRAFIA, ART*/

INSERT INTO CATEGORIA

VALUES (1, 'CIENCIA');

INSERT INTO CATEGORIA

VALUES (2, 'ESPORTS');

INSERT INTO CATEGORIA

VALUES (3, 'ENTRETENIMENT');

INSERT INTO CATEGORIA

VALUES (4, 'HISTORIA');

INSERT INTO CATEGORIA

VALUES (5, 'GEOGRAFIA');

INSERT INTO CATEGORIA

VALUES (6, 'ART');




/*INSERIM PREGUNTES*/



/*CIENCIAS*/

INSERT INTO PREGUNTA

VALUES(1, 1, '¿CUAL ES LA FÓRMULA DEL AGUA?');

INSERT INTO PREGUNTA

VALUES(2, 1,'CUANTAS CALORIAS TIENE UN VASO DE AGUA?');

INSERT INTO PREGUNTA

VALUES(3, 1, 'CUAL DE LAS SIGUIENTES ENFERMEDADES ATACA EL HIGADO');

INSERT INTO PREGUNTA

VALUES(4, 1, 'QUÉ CAMBIO DE ESTADO DA A LA SUBLIMACIÓN?');

INSERT INTO PREGUNTA

VALUES(5, 1, 'DE QUÉ COLOR TIENEN LA SANGRE LOS PECES?');

INSERT INTO PREGUNTA

VALUES(6, 1, 'CUANTAS CARAS TIENE UN ICOSAEDRO?');

INSERT INTO PREGUNTA

VALUES(7, 1, 'CUAL ES EL MAMIFERO MÁS GRANDE CONOCIDO?');

INSERT INTO PREGUNTA

VALUES(8, 1, 'DÓNDE ESTÁ EL MENISCO?');

INSERT INTO PREGUNTA

VALUES(9, 1, 'QUÉ TRANSFORMA LA LECHE EN YOGURT?');

INSERT INTO PREGUNTA

VALUES(10, 1, 'QUÉ ES PLUTÓN?');



/*DEPORTES*/

INSERT INTO PREGUNTA

VALUES(11, 2, 'CUAL DE LOS SIGUIENTES DEPORTES ES DE PRECISIÓN?');

INSERT INTO PREGUNTA

VALUES(12, 2, 'CUANTAS VECES HA GANADO EL MUNDIAL DE FUTBOL ESPAÑA?');

INSERT INTO PREGUNTA

VALUES(13, 2, 'CUAL DE ESTOS TORNEOS FORMA PARTE DEL GRAN SLAM?');

INSERT INTO PREGUNTA

VALUES(14, 2, 'QUIÉN FUE EL GANADOR DEL MUNDIAL DE F1 EN 2014?');

INSERT INTO PREGUNTA  

VALUES(15, 2, 'CUANTAS BOLAS TIENE EL BILLAR AMERICANO?');

INSERT INTO PREGUNTA

VALUES(16, 2, 'CUANTOS EQUIPOS PARTICIPAN EN EL ACB EN 2016?');

INSERT INTO PREGUNTA

VALUES(17, 2, 'QUIÉN ES EL CAMPEÓN MUNDIAL DE DARDOS?');

INSERT INTO PREGUNTA

VALUES(18, 2, 'QUE EQUIPO GANÓ LA LIGA DE CAMPEONES DE LA TEMPORADA 2015-2016?');

INSERT INTO PREGUNTA

VALUES(19, 2, 'EN QUE EQUIPO DEBUTO VALENTINO ROSSI EN 500cc(ACUAL MOTOGP)?');

INSERT INTO PREGUNTA

VALUES(20, 2, 'CUANTÁS MEDALLAS DE ORO CONSIGUIÓ MICHAEL PHELPS EN LAS OLIMPIADAS DE RIO 2016');




/*ENTRETENIMENTO*/

INSERT INTO PREGUNTA

VALUES(21, 3, 'DE QUIÉN ES LA CANCIÓN IMAGINE?');

INSERT INTO PREGUNTA

VALUES(22, 3, 'EN QUÉ AÑO SE ESTRENO LA PALÍCULA PINOCHO?');

INSERT INTO PREGUNTA

VALUES(23, 3, 'QUIÉN ES LA MASCOTA DE SEGA');

INSERT INTO PREGUNTA

VALUES(24, 3, 'CÓMO SE LLAMA EL PERSONEJE QUE INTERPRETA ALPACINO EN SCARFACE?');

INSERT INTO PREGUNTA

VALUES(25, 3, 'COMO SE LLAMA EL PROTAGONISTA DE LA SAGA INDIANA JONES?');

INSERT INTO PREGUNTA

VALUES(26, 3, 'QUÉ ANIMAL ES LA MASCOTA DE JASMINE EN ALADÍN?');

INSERT INTO PREGUNTA

VALUES(27, 3, 'QUIÉN DE ELLAS ES UNA CANTANTE ESPAÑOLA?');

INSERT INTO PREGUNTA

VALUES(28, 3, 'A QUIÉN SE LE CONSIDERA EL REY DEL ROCK?');

INSERT INTO PREGUNTA

VALUES(29, 3, 'QUÉ DIA ES SAN VALENTIN?');

INSERT INTO PREGUNTA

VALUES(30, 3, 'COMO SE LLAMA EL MARIDO DE MAITE FIGUEROA (CUKI) EN LA QUE SE AVECINA?');



/*HISTORIA*/

INSERT INTO PREGUNTA

VALUES(31, 4, 'CUANDO EMPEZO LA GUERRA CIVIL ESPAÑOLA');

INSERT INTO PREGUNTA

VALUES(32, 4, 'EN QUÉ AÑO FUE ATACADO PEARL HARBOUR DURANTE LA IIWW?');

INSERT INTO PREGUNTA

VALUES(33, 4, 'CON QUÉ EMPERADOR ESTUVO CASADO CLEOPATRA?');

INSERT INTO PREGUNTA

VALUES(34, 4, 'CÓMO SE LLAMABA EL PRIMER CONTINENTE DE LA HISTORIA?');

INSERT INTO PREGUNTA

VALUES(35, 4, 'QUÉ UNIÓN DE PAÏSES FUÉ GOBERNADO POR STALIN?');

INSERT INTO PREGUNTA

VALUES(36, 4, 'CUÁNTO DURO E SIGLO DE ORO?');

INSERT INTO PREGUNTA

VALUES(37, 4, 'QUIÉN LIBERÓ ARGENTINA, CHILE Y PERÚ?');

INSERT INTO PREGUNTA

VALUES(38, 4, 'DÓNDE NACIÓ LA FILOSOFÍA?');

INSERT INTO PREGUNTA

VALUES(39, 4, 'EN QUÉ AÑO SE DESCUBRIÓ AMERICA?');

INSERT INTO PREGUNTA

VALUES(40, 4, 'QUIÉN FUÉ EL ÚLTIMO REY FRANCÉS?');



/*GEOGRAFIA*/

INSERT INTO PREGUNTA

VALUES(41, 5, 'CUÁL DE LOS SIGUIENTES PAÍSES NO TIENE DESIERTO?');

INSERT INTO PREGUNTA

VALUES(42, 5, 'CON CUANTOS PAÍSES LIMÍTA ARGENTINA?');

INSERT INTO PREGUNTA

VALUES(43, 5, 'CUÁL ES LA CAPITAL DE SUIZA?');

INSERT INTO PREGUNTA

VALUES(44, 5, 'CUÁNTOS CONTINENTES HAY EN EL MUNDO?');

INSERT INTO PREGUNTA

VALUES(45, 5, 'DÓNDE ESTÁ EL DESIERTO DEL GOBI?');

INSERT INTO PREGUNTA

VALUES(46, 5, 'CUÁL ES LA CAPITAL DE MADAGACAR?');

INSERT INTO PREGUNTA

VALUES(47, 5, 'CUÁL ES LA CIUDAD MÁS PEQUEÑA DEL MUNDO?');

INSERT INTO PREGUNTA

VALUES(48, 5, 'DÓNDE ESTÁ LA SERRALADA DE LOS ANDÉS?');

INSERT INTO PREGUNTA

VALUES(49, 5, 'DE QUÉ PAÍS FORMA PARTE GROENLANDIA?');

INSERT INTO PREGUNTA

VALUES(50, 5, 'CUÁNTAS ESTRELLAS TIENE LA BANDERA CHINA?');



/*ARTE*/

INSERT INTO PREGUNTA

VALUES(51, 6, 'QUIÉN ESCRIBIÓ EL DIARIO DE ANA FRANK?');

INSERT INTO PREGUNTA

VALUES(52, 6, 'QUIÉN ESCRIBIÓ EL LIBRO DE MOBY DICK?');

INSERT INTO PREGUNTA

VALUES(53, 6, 'QUIÉN PINTÓ LAS MENINAS?');

INSERT INTO PREGUNTA

VALUES(54, 6, 'CON QUE NOMBRE FIRMABA PABLO PICASSO?');

INSERT INTO PREGUNTA

VALUES(55, 6, 'EN QUE SIGLO NACIÓ EL ARTISTA CONOCIDO COMO CARAVAGGIO?');

INSERT INTO PREGUNTA

VALUES(56, 6, 'QUIÉN FUE ANTONI LUCIO VIVALDI?');

INSERT INTO PREGUNTA

VALUES(57, 6, 'QUIÉN PINTÓ LA CAPILLA SIXTINA?');

INSERT INTO PREGUNTA

VALUES(58, 6, 'CUÁL FUE LA NOVELA MÁS IMPORTANTE ESCRITA POR DANTE ALIGIERI?');

INSERT INTO PREGUNTA

VALUES(59, 6, 'QUIÉN ESCRIBIÓ DON JUAN TENORIO?');

INSERT INTO PREGUNTA

VALUES(60, 6, 'QUIÉN ESCRIBIÓ LAZARILLO DE TORMES?');

/*CIENCIA*/
INSERT INTO RESPOSTA 
VALUES (1, 1, 'H2O', TRUE);
INSERT INTO RESPOSTA
VALUES(1, 2, 'HO', FALSE);
INSERT INTO RESPOSTA
VALUES(1, 3, 'HO2', FALSE);
INSERT INTO RESPOSTA
VALUES(1, 4, 'AGU', FALSE);

INSERT INTO RESPOSTA
VALUES (2, 1, '0', TRUE);
INSERT INTO RESPOSTA
VALUES(2, 2,'10', FALSE);
INSERT INTO RESPOSTA
VALUES(2, 3,'100', FALSE);
INSERT INTO RESPOSTA
VALUES(2, 4, '20', FALSE);

INSERT INTO RESPOSTA
VALUES (3, 1, 'HEPATITIS', TRUE);
INSERT INTO RESPOSTA
VALUES(3, 2,'DIABETES', FALSE);
INSERT INTO RESPOSTA
VALUES(3, 3,'ARTROSIS', FALSE);
INSERT INTO RESPOSTA
VALUES(3, 4,'ESCOLIOSI', FALSE);

INSERT INTO RESPOSTA
VALUES (4, 1, 'SÓLIDO A GASEOSO', TRUE);
INSERT INTO RESPOSTA
VALUES(4, 2, 'SÓLIDO A LÍQUIDO', FALSE);
INSERT INTO RESPOSTA
VALUES(4, 3, 'GASEOSO A SÓLIDO', FALSE);
INSERT INTO RESPOSTA
VALUES(4, 4, 'LÍQUIDO A SÓLIDO', FALSE);

INSERT INTO RESPOSTA
VALUES (5, 1, 'ROJA', TRUE);
INSERT INTO RESPOSTA
VALUES(5, 2, 'AZUL', FALSE);
INSERT INTO RESPOSTA
VALUES(5, 3,'VERDE', FALSE);
INSERT INTO RESPOSTA
VALUES(5, 4,'MARRÓN', FALSE);

INSERT INTO RESPOSTA
VALUES (6, 1, '20', TRUE);
INSERT INTO RESPOSTA
VALUES(6, 2,'12', FALSE);
INSERT INTO RESPOSTA
VALUES(6, 3,'32', FALSE);
INSERT INTO RESPOSTA
VALUES(6, 4,'4', FALSE);

INSERT INTO RESPOSTA
VALUES (7, 1,'BALLENA AZUL', TRUE);
INSERT INTO RESPOSTA
VALUES(7, 2,'ELEFANTE', FALSE);
INSERT INTO RESPOSTA
VALUES(7, 3,'JIRAFA', FALSE);
INSERT INTO RESPOSTA
VALUES(7, 4,'RINOCERONTE', FALSE);

INSERT INTO RESPOSTA
VALUES (8, 1,'RODILLA', TRUE);
INSERT INTO RESPOSTA
VALUES(8, 2,'CODO', FALSE);
INSERT INTO RESPOSTA
VALUES(8, 3,'ESPALDA', FALSE);
INSERT INTO RESPOSTA
VALUES(8, 4,'PIE', FALSE);

INSERT INTO RESPOSTA
VALUES (9, 1,'UNA BACTÉRIA', TRUE);
INSERT INTO RESPOSTA
VALUES(9, 2,'UN VIRUS', FALSE);
INSERT INTO RESPOSTA
VALUES(9, 3,'EL TIEMPO', FALSE);
INSERT INTO RESPOSTA
VALUES(9, 4,'NINGUNA DE LAS ANTERIORES', FALSE);

INSERT INTO RESPOSTA
VALUES (10, 1,'PLANETA ENANO', TRUE);
INSERT INTO RESPOSTA
VALUES(10, 2,'SATELITE', FALSE);
INSERT INTO RESPOSTA
VALUES(10, 3,'PLUTOIDE', FALSE);
INSERT INTO RESPOSTA
VALUES(10, 4,'PLANETA', FALSE);

/*ESPORT*/
INSERT INTO RESPOSTA
VALUES (11, 1,'BILLAR', TRUE);
INSERT INTO RESPOSTA
VALUES(11, 2,'BOLOS', FALSE);
INSERT INTO RESPOSTA
VALUES(11, 3,'FÚTBOL', FALSE);
INSERT INTO RESPOSTA
VALUES(11, 4,'TENIS', FALSE);

INSERT INTO RESPOSTA
VALUES (12, 1,'1', TRUE);
INSERT INTO RESPOSTA
VALUES(12, 2,'2', FALSE);
INSERT INTO RESPOSTA
VALUES(12, 3,'0', FALSE);
INSERT INTO RESPOSTA
VALUES(12, 4,'4', FALSE);

INSERT INTO RESPOSTA
VALUES (13, 1,'WIMBLEDON', TRUE);
INSERT INTO RESPOSTA
VALUES(13, 2,'MUTUA MADRID OPEN', FALSE);
INSERT INTO RESPOSTA
VALUES(13, 3,'MIAMI OPEN', FALSE);
INSERT INTO RESPOSTA
VALUES(13, 4,'ROGERS CUP', FALSE);

INSERT INTO RESPOSTA
VALUES (14, 1,'LEWIS HAMILTON', TRUE);
INSERT INTO RESPOSTA
VALUES(14, 2,'SEBASTIAN VETTEL', FALSE);
INSERT INTO RESPOSTA
VALUES(14, 3,'NICO ROSBERG', FALSE);
INSERT INTO RESPOSTA
VALUES(14, 4,'JENSON BUTTON', FALSE);

INSERT INTO RESPOSTA
VALUES (15, 1,'16', TRUE);
INSERT INTO RESPOSTA
VALUES(15, 2,'15', FALSE);
INSERT INTO RESPOSTA
VALUES(15, 3,'14', FALSE);
INSERT INTO RESPOSTA
VALUES(15, 4,'17', FALSE);

INSERT INTO RESPOSTA
VALUES (16, 1,'17', TRUE);
INSERT INTO RESPOSTA
VALUES(16, 2,'16', FALSE);
INSERT INTO RESPOSTA
VALUES(16, 3,'20', FALSE);
INSERT INTO RESPOSTA
VALUES(16, 4,'12', FALSE);

INSERT INTO RESPOSTA
VALUES (17, 1,'GARY ANDERSON', TRUE);
INSERT INTO RESPOSTA
VALUES(17, 2,'ADRIAN LEWIS', FALSE);
INSERT INTO RESPOSTA
VALUES(17, 3,'LEWIS HAMILTON', FALSE);
INSERT INTO RESPOSTA
VALUES(17, 4,'MICHAEL SMITH', FALSE);

INSERT INTO RESPOSTA
VALUES (18, 1,'REAL MADRID', TRUE);
INSERT INTO RESPOSTA
VALUES(18, 2,'FCB', FALSE);
INSERT INTO RESPOSTA
VALUES(18, 3,'MANCHESTER CITY', FALSE);
INSERT INTO RESPOSTA
VALUES(18, 4,'ATLÉTICO DE MADRID', FALSE);

INSERT INTO RESPOSTA
VALUES (19, 1,'HONDA', TRUE);
INSERT INTO RESPOSTA
VALUES(19, 2,'YAMAHA', FALSE);
INSERT INTO RESPOSTA
VALUES(19, 3,'DUCATI', FALSE);
INSERT INTO RESPOSTA
VALUES(19, 4,'KAWASAKI', FALSE);

INSERT INTO RESPOSTA
VALUES (20, 1,'5', TRUE);
INSERT INTO RESPOSTA
VALUES(20, 2,'1', FALSE);
INSERT INTO RESPOSTA
VALUES(20, 3,'2', FALSE);
INSERT INTO RESPOSTA
VALUES(20, 4,'6', FALSE);

/*ENTRETENIMENT*/
INSERT INTO RESPOSTA
VALUES (21, 1, 'JOHN LENNON', TRUE);
INSERT INTO RESPOSTA
VALUES(21, 2,'JOHN LEMMON', FALSE);
INSERT INTO RESPOSTA
VALUES(21, 3,'PAUL MCCARTNEY', FALSE);
INSERT INTO RESPOSTA
VALUES(21, 4,'RINGO STAR', FALSE);

INSERT INTO RESPOSTA
VALUES (22, 1,'1940', TRUE);
INSERT INTO RESPOSTA
VALUES(22, 2,'1950', FALSE);
INSERT INTO RESPOSTA
VALUES(22, 3,'1952', FALSE);
INSERT INTO RESPOSTA
VALUES(22, 4,'1946', FALSE);

INSERT INTO RESPOSTA
VALUES (23, 1,'SONIC', TRUE);
INSERT INTO RESPOSTA
VALUES(23, 2,'MARIO', FALSE);
INSERT INTO RESPOSTA
VALUES(23, 3,'PACMAN', FALSE);
INSERT INTO RESPOSTA
VALUES(23, 4,'RYU', FALSE);

INSERT INTO RESPOSTA
VALUES (24, 1,'TONY MONTANA', TRUE);
INSERT INTO RESPOSTA
VALUES(24, 2,'MICHAEL CORLEONE', FALSE);
INSERT INTO RESPOSTA
VALUES(24, 3,'FRANK SLADE', FALSE);
INSERT INTO RESPOSTA
VALUES(24, 4,'SONNY MONTANA', FALSE);

INSERT INTO RESPOSTA
VALUES (25, 1,'HARRISSON FORD', TRUE);
INSERT INTO RESPOSTA
VALUES(25, 2,'JACK NICHOLSON', FALSE);
INSERT INTO RESPOSTA
VALUES(25, 3,'ROBIN WILLIAMS', FALSE);
INSERT INTO RESPOSTA
VALUES(25, 4,'MICHAEL FOX', FALSE);

INSERT INTO RESPOSTA
VALUES (26, 1,'TIGRE', TRUE);
INSERT INTO RESPOSTA
VALUES(26, 2,'MONO', FALSE);
INSERT INTO RESPOSTA
VALUES(26, 3,'SERPIENTE', FALSE);
INSERT INTO RESPOSTA
VALUES(26, 4,'ELEFANTE', FALSE);

INSERT INTO RESPOSTA
VALUES (27, 1,'CHENOA', TRUE);
INSERT INTO RESPOSTA
VALUES(27, 2,'ARIANA GRANDE', FALSE);
INSERT INTO RESPOSTA
VALUES(27, 3,'JENNIFER LOPEZ', FALSE);
INSERT INTO RESPOSTA
VALUES(27, 4,'ALASKA', FALSE);

INSERT INTO RESPOSTA
VALUES (28, 1,'MICHAEL JACKSON', TRUE);
INSERT INTO RESPOSTA
VALUES(28, 2,'JUSTIN BIEBER', FALSE);
INSERT INTO RESPOSTA
VALUES(28, 3,'ELVIS PRESLEY', FALSE);
INSERT INTO RESPOSTA
VALUES(28, 4,'ZAYN MALIK', FALSE);

INSERT INTO RESPOSTA
VALUES (29, 1,'14-FEBRERO', TRUE);
INSERT INTO RESPOSTA
VALUES(29, 2,'14-MARZO', FALSE);
INSERT INTO RESPOSTA
VALUES(29, 3,'15 FEBRERO', FALSE);
INSERT INTO RESPOSTA
VALUES(29, 4,'18 DE FEBRERO', FALSE);

INSERT INTO RESPOSTA
VALUES (30, 1,'AMADOR RIVAS', TRUE);
INSERT INTO RESPOSTA
VALUES(30, 2,'ANTONIO RECIO', FALSE);
INSERT INTO RESPOSTA
VALUES(30, 3,'SERGIO ARIAS', FALSE);
INSERT INTO RESPOSTA
VALUES(30, 4,'ENRIQUE PASTOR', FALSE);

/*HISTÒRIA*/
INSERT INTO RESPOSTA
VALUES (31, 1,'1936', TRUE);
INSERT INTO RESPOSTA
VALUES(31, 2,'1937', FALSE);
INSERT INTO RESPOSTA
VALUES(31, 3,'1939', FALSE);
INSERT INTO RESPOSTA
VALUES(31, 4,'1940', FALSE);

INSERT INTO RESPOSTA
VALUES (32, 1,'1941', TRUE);
INSERT INTO RESPOSTA
VALUES(32, 2,'1936', FALSE);
INSERT INTO RESPOSTA
VALUES(32, 3,'1945', FALSE);
INSERT INTO RESPOSTA
VALUES(32, 4,'1939', FALSE);

INSERT INTO RESPOSTA
VALUES (33, 1,'TODAS SON CORRECTAS', TRUE);
INSERT INTO RESPOSTA
VALUES(33, 2,'PTOLOMEO', FALSE);
INSERT INTO RESPOSTA
VALUES(33, 3,'JULIO CESAR', FALSE);
INSERT INTO RESPOSTA
VALUES(33, 4,'MARCO ANTONIO', FALSE);

INSERT INTO RESPOSTA
VALUES (34, 1,'PANGEA', TRUE);
INSERT INTO RESPOSTA
VALUES(34, 2,'EUROPA', FALSE);
INSERT INTO RESPOSTA
VALUES(34, 3,'URSS', FALSE);
INSERT INTO RESPOSTA
VALUES(34, 4,'PANGERA', FALSE);

INSERT INTO RESPOSTA
VALUES (35, 1,'URSS', TRUE);
INSERT INTO RESPOSTA
VALUES(35, 2,'CUBA', FALSE);
INSERT INTO RESPOSTA
VALUES(35, 3,'ALEMANIA', FALSE);
INSERT INTO RESPOSTA
VALUES(35, 4,'RUSIA', FALSE);

INSERT INTO RESPOSTA
VALUES (36, 1,'2', TRUE);
INSERT INTO RESPOSTA
VALUES(36, 2, '1', FALSE);
INSERT INTO RESPOSTA
VALUES(36, 3,'3', FALSE);
INSERT INTO RESPOSTA
VALUES(36, 4, '4', FALSE);

INSERT INTO RESPOSTA
VALUES (37, 1, 'JOSÉ DE SANMARTÍN', TRUE);
INSERT INTO RESPOSTA
VALUES(37, 2, 'ERNESTO CHE GUEVARA', FALSE);
INSERT INTO RESPOSTA
VALUES(37, 3, 'SIMÓN BOLIVAR', FALSE);
INSERT INTO RESPOSTA
VALUES(37, 4, 'MANUAL BELGRANO', FALSE);

INSERT INTO RESPOSTA
VALUES (38, 1, 'GRÉCIA', TRUE);
INSERT INTO RESPOSTA
VALUES(38, 2, 'ITÁLIA', FALSE);
INSERT INTO RESPOSTA
VALUES(38, 3, 'ESPAÑAA', FALSE);
INSERT INTO RESPOSTA
VALUES(38, 4, 'EGIPTO', FALSE);

INSERT INTO RESPOSTA
VALUES (39, 1, '1492', TRUE);
INSERT INTO RESPOSTA
VALUES(39, 2, '1942', FALSE);
INSERT INTO RESPOSTA
VALUES(39, 3, '1788', FALSE);
INSERT INTO RESPOSTA
VALUES(39, 4, '1592', FALSE);

INSERT INTO RESPOSTA
VALUES (40, 1, 'LUIS FELIPE I DE FRANCIA', TRUE);
INSERT INTO RESPOSTA
VALUES(40, 2, 'LUIS 16', FALSE);
INSERT INTO RESPOSTA
VALUES(40, 3, 'ENRIQUE 4', FALSE);
INSERT INTO RESPOSTA
VALUES(40, 4, 'CARLOS 10', FALSE);

/*GEOGRAFÍA*/
INSERT INTO RESPOSTA
VALUES (41, 1, 'ALEMAÑA', TRUE);
INSERT INTO RESPOSTA
VALUES(41, 2, 'FRANCIA', FALSE);
INSERT INTO RESPOSTA
VALUES(41, 3, 'ESPAÑA', FALSE);
INSERT INTO RESPOSTA
VALUES(41, 4, 'MONGÓLIA', FALSE);

INSERT INTO RESPOSTA
VALUES (42, 1,'5', TRUE);
INSERT INTO RESPOSTA
VALUES(42, 2, '6', FALSE);
INSERT INTO RESPOSTA
VALUES(42, 3, '4', FALSE);
INSERT INTO RESPOSTA
VALUES(42, 4, '3', FALSE);

INSERT INTO RESPOSTA
VALUES (43, 1, 'BERNA', TRUE);
INSERT INTO RESPOSTA
VALUES(43, 2, 'ZURICH', FALSE);
INSERT INTO RESPOSTA
VALUES(43, 3, 'GINEBRA', FALSE);
INSERT INTO RESPOSTA
VALUES(43, 4, 'BERLÍN', FALSE);

INSERT INTO RESPOSTA
VALUES (44, 1, '6', TRUE);
INSERT INTO RESPOSTA
VALUES(44, 2, '5', FALSE);
INSERT INTO RESPOSTA
VALUES(44, 3, '4', FALSE);
INSERT INTO RESPOSTA
VALUES(44, 4, '7', FALSE);

INSERT INTO RESPOSTA
VALUES (45, 1, 'SUD DE MONGÓLIA', TRUE);
INSERT INTO RESPOSTA
VALUES(45, 2, 'SUD DE CHINA', FALSE);
INSERT INTO RESPOSTA
VALUES(45, 3, 'SUD DEL JAPÓN', FALSE);
INSERT INTO RESPOSTA
VALUES(45, 4, 'NINGUNA DE LAS ANTERIORES', FALSE);

INSERT INTO RESPOSTA
VALUES (46, 1, 'ANTANANARIVO', TRUE);
INSERT INTO RESPOSTA
VALUES(46, 2, 'BRAZZAVILLE', FALSE);
INSERT INTO RESPOSTA
VALUES(46, 3, 'RABAT', FALSE);
INSERT INTO RESPOSTA
VALUES(46, 4, 'EL CAIRO', FALSE);

INSERT INTO RESPOSTA
VALUES (47, 1, 'CIUDAD DEL VATICANO', TRUE);
INSERT INTO RESPOSTA
VALUES(47, 2, 'ANDORRA', FALSE);
INSERT INTO RESPOSTA
VALUES(47, 3, 'ROMA', FALSE);
INSERT INTO RESPOSTA
VALUES(47, 4, 'FLORÉNCIA', FALSE);

INSERT INTO RESPOSTA
VALUES (48, 1, 'AMÉRICA DEL SUD', TRUE);
INSERT INTO RESPOSTA
VALUES(48, 2, 'AMÉRICA DEL NORD', FALSE);
INSERT INTO RESPOSTA
VALUES(48, 3, 'EUROPA', FALSE);
INSERT INTO RESPOSTA
VALUES(48, 4, 'ÁSIA', FALSE);

INSERT INTO RESPOSTA
VALUES (49, 1, 'DINAMARCA', TRUE);
INSERT INTO RESPOSTA
VALUES(49, 2, 'SUIZA', FALSE);
INSERT INTO RESPOSTA
VALUES(49, 3, 'CANADÁ', FALSE);
INSERT INTO RESPOSTA
VALUES(49, 4, 'EEUU', FALSE);

INSERT INTO RESPOSTA
VALUES (50, 1, '5', TRUE);
INSERT INTO RESPOSTA
VALUES(50, 2, '2', FALSE);
INSERT INTO RESPOSTA
VALUES(50, 3, '3', FALSE);
INSERT INTO RESPOSTA
VALUES(50, 4, '1', FALSE);

/*ART*/
INSERT INTO RESPOSTA
VALUES (51, 1, 'ANA FRANK', TRUE);
INSERT INTO RESPOSTA
VALUES(51, 2, 'ANÓNIMO', FALSE);
INSERT INTO RESPOSTA
VALUES(51, 3, 'HITLER', FALSE);
INSERT INTO RESPOSTA
VALUES(51, 4, 'SHINDLER', FALSE);

INSERT INTO RESPOSTA
VALUES (52, 1, 'HERMAN MELVILLE', TRUE);
INSERT INTO RESPOSTA
VALUES(52, 2, 'HENRY DAVID THOREAU', FALSE);
INSERT INTO RESPOSTA
VALUES(52, 3, 'RALPH WALDO EMERSON', FALSE);
INSERT INTO RESPOSTA
VALUES(52, 4, 'HENRY JAMES', FALSE);

INSERT INTO RESPOSTA
VALUES (53, 1, 'DIEGO VELÁZQUEZ', TRUE);
INSERT INTO RESPOSTA
VALUES(53, 2, 'PABLO PICASSO', FALSE);
INSERT INTO RESPOSTA
VALUES(53, 3, 'LEONARDO DA VINCI', FALSE);
INSERT INTO RESPOSTA
VALUES(53, 4, 'JOAN MIRÓ', FALSE);

INSERT INTO RESPOSTA
VALUES (54, 1, 'PICASSO', TRUE);
INSERT INTO RESPOSTA
VALUES(54, 2, 'P. PICASSO', FALSE);
INSERT INTO RESPOSTA
VALUES(54, 3, 'PABLO PICASSO', FALSE);
INSERT INTO RESPOSTA
VALUES(54, 4, 'PABLO PICACHU', FALSE);

INSERT INTO RESPOSTA
VALUES (55, 1, 'XVI', TRUE);
INSERT INTO RESPOSTA
VALUES(55, 2, 'XV', FALSE);
INSERT INTO RESPOSTA
VALUES(55, 3, 'XVII', FALSE);
INSERT INTO RESPOSTA
VALUES(55, 4, 'XIV', FALSE);

INSERT INTO RESPOSTA
VALUES (56, 1, 'UN VIOLINISTA', TRUE);
INSERT INTO RESPOSTA
VALUES(56, 2, 'UN CONTRABAJISTA', FALSE);
INSERT INTO RESPOSTA
VALUES(56, 3, 'UN PINTOR', FALSE);
INSERT INTO RESPOSTA
VALUES(56, 4, 'UN PIANISTA', FALSE);

INSERT INTO RESPOSTA
VALUES (57, 1, 'MIGUEL ÁNGEL', TRUE);
INSERT INTO RESPOSTA
VALUES(57, 2, 'LEONARDO DA VINCI', FALSE);
INSERT INTO RESPOSTA
VALUES(57, 3, 'TIZIANO', FALSE);
INSERT INTO RESPOSTA
VALUES(57, 4, 'GIORGIO VASARI', FALSE);

INSERT INTO RESPOSTA
VALUES (58, 1, 'LA DIVINA COMÉDIA', TRUE);
INSERT INTO RESPOSTA
VALUES(58, 2, 'VITA NUOVA', FALSE);
INSERT INTO RESPOSTA
VALUES(58, 3, 'DE VULGARI ELOQUENTIA', FALSE);
INSERT INTO RESPOSTA
VALUES(58, 4, 'NINGUNA DE LAS ANTERIORES', FALSE);

INSERT INTO RESPOSTA
VALUES (59, 1, 'JOSÉ ZORRILLA', TRUE);
INSERT INTO RESPOSTA
VALUES(59, 2, 'ESPRONCEDA', FALSE);
INSERT INTO RESPOSTA
VALUES(59, 3, 'GARCÍA LORCA', FALSE);
INSERT INTO RESPOSTA
VALUES(59, 4, 'FERNANDO DE ROJAS', FALSE);

INSERT INTO RESPOSTA
VALUES (60, 1, 'DIEGO HURTADO DE MENDOZA', TRUE);
INSERT INTO RESPOSTA
VALUES(60, 2, 'ANÓNIMO', FALSE);
INSERT INTO RESPOSTA
VALUES(60, 3, 'MERCEDES AGULLÓ', FALSE);
INSERT INTO RESPOSTA
VALUES(60, 4, 'FRANCISCO DE RIOJA', FALSE);